### ISSUE TITLE
Invalid menu ID:

### ISSUE THREAD

**Issue by ideasman42** [yotsugi0704/Selected_Bones_To_Vertex_Group#1]
On registering, this messages is shown in the console.
```
register_class(...):
Warning: 'object.add_del_menu' does not contain '_MT_' with prefix and suffix
```

**Comment by yotsugi0704** [comment]
Got it! I’ll test this issue later.

**Comment by yotsugi0704** [comment]
> On registering, this messages is shown in the console.
> 
> ```
> register_class(...):
> Warning: 'object.add_del_menu' does not contain '_MT_' with prefix and suffix
> ```

Thanks for your report, I have already updated to version 1.0.1 to fix this!
